@host = http://localhost:3000/api

###
# GET ALL CARDS
GET {{host}}/card

###
# GET CARD
GET {{host}}/card/1

###
# CREATE CARD
POST {{host}}/card/create
Content-Type: application/json

{
    "listId": 1,
    "title": "dummy card",
    "content": "dummy card's content",
    "dueDateValue": "2024-01-10",
    "dueTimeValue": "20:00"
}

### 
# UPDATE CARD
PATCH  {{host}}/card/1
Content-Type: application/json

{
	"title": "first card!!!"
}

### 
# UPDATE CARD ORDER (현재 카드아이디 값/옮기고 싶은 위치의 카드 order 값)
PATCH {{host}}/card/9/13

### 
# DELETE CARD
DELETE {{host}}/card/delete/5
  
### 
#CREATE WORKER
POST {{host}}/card/2/worker/create
Content-Type: application/json

{
  "userIds": [
    { "id": 1 },
    { "id": 2 }
  ]
}

###
# DELETE WORKER
DELETE {{host}}/card/2/worker/remove/1

