@host = http://localhost:3000
@Token = {{login.response.body.$.accessToken}}

// user
### 회원가입
POST {{host}}/api/user/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "nick": "test",
  "password": "1q2w3e4r1234",
  "passwordConfirm": "1q2w3e4r1234"
}

### 로그인
# @name login
POST {{host}}/api/user/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1q2w3e4r1234"
}

### 내 정보 조회
GET {{host}}/api/user/myinfo
Authorization: Bearer {{Token}}
Content-Type: application/json

// 보드
### 보드 생성
POST {{host}}/api/boards
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "title": "새 보드",
  "color": "blue"
}

### 전체 보드 목록 조회
GET {{host}}/api/boards
Authorization: Bearer {{Token}}

### 특정 보드 조회
GET {{host}}/api/boards/3
Authorization: Bearer {{Token}}

### 보드 수정(오류)
PATCH {{host}}/api/boards/3
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "title": "수정된 보드 제목",
  "color": "red"
}

### 보드 삭제
DELETE {{host}}/boards/1

// 리스트 테스트
### 리스트등록
POST {{host}}/api/list
Content-Type: application/json

{
  "boards_id": 1,
  "title": "Done"
}

### 리스트보기
GET {{host}}/api/list/all/1
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 리스트 보기
GET {{host}}/api/list/1
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 예약 타이틀수정
PATCH {{host}}/api/list/1
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "title": "Todos1"
}

### 특정 예약 순서수정
PATCH {{host}}/api/list/1/5
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 예약 삭제
DELETE {{host}}/api/list/1
Authorization: Bearer {{Token}}
Content-Type: application/json